#change this
footprint: [[0.3345, 0.223],
            [0.3345, 0.1],
            [0.55, 0.1],
            [0.55, -0.1],
            [0.3345, -0.1],
            [0.3345, -0.223],
            [-0.3345, -0.223],
            [-0.3345, 0.223]]

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.25
footprint_padding: 0.03

